—
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket for {{ env['ENVIRONMENT_NAME'] }}

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
    BucketName: InstallFiles-{{ env['AWS_ACCOUNT_NUMBER'] }}